version: '3.7'

services:
  backend:
    build:
      context: ./backend/onereturn
    command: gunicorn onereturn.wsgi --bind 0.0.0.0:8000 --workers=5 --threads=2
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend/onereturnfe
    volumes:
      - react_build:/react/build
  merchant-frontend:
    build:
      context: ./merchant-console
    volumes:
      - merchant-react-build:/merchant-app/build
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
      - merchant-react-build:/var/www/merchant-react
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
  merchant-react-build: