# Generated by Django 4.1.4 on 2024-03-27 00:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('uuid', models.CharField(default=None, max_length=100, unique=True)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emailVerified', models.BooleanField(default=False)),
                ('phoneVerifed', models.BooleanField(default=False)),
                ('regComplete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientID', models.CharField(default=None, max_length=100)),
                ('merchantID', models.CharField(default=None, max_length=100)),
                ('merchantLocNumber', models.CharField(default=None, max_length=100)),
                ('merchantAddress', models.CharField(default=None, max_length=100)),
                ('merchantName', models.CharField(default=None, max_length=100)),
                ('invoiceID', models.CharField(default=None, max_length=100)),
                ('dateCreated', models.DateTimeField(default=None)),
                ('flagged', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0.0)),
                ('cards_used', models.CharField(max_length=4, null=True)),
                ('transactionHistory', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=100), default=list, size=None)),
                ('sharedWith', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedMerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantID', models.CharField(default=None, max_length=100, null=True)),
                ('businessName', models.CharField(default=None, max_length=100, null=True)),
                ('businessAddress', models.CharField(default=None, max_length=100, null=True)),
                ('businessType', models.CharField(default=None, max_length=100, null=True)),
                ('industry', models.CharField(default=None, max_length=100, null=True)),
                ('primaryContactName', models.CharField(default=None, max_length=100, null=True)),
                ('primaryPhoneNumber', models.CharField(default=None, max_length=100, null=True)),
                ('numRegisters', models.CharField(default=None, max_length=100, null=True)),
                ('emailVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('returned', models.BooleanField(default=False)),
                ('returnedBy', models.CharField(default=None, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('originalVendor', models.CharField(default=None, max_length=100)),
                ('itemCategory', models.CharField(default=None, max_length=100)),
                ('itemSku', models.CharField(default=None, max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('paymentMethod', models.CharField(default=None, max_length=100)),
                ('cardInfo', models.CharField(default=None, max_length=4, null=True)),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usageThisMonth', models.CharField(default=0, max_length=255)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.merchantaccount')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='sharedInvoices',
            field=models.ManyToManyField(to='core.invoice'),
        ),
    ]
