# Generated by Django 4.1.4 on 2024-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='usageThisMonth',
        ),
        migrations.AddField(
            model_name='apikey',
            name='keyID',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
