# Generated by Django 4.1.4 on 2023-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipientID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
