# Generated by Django 4.1.7 on 2023-05-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_recipientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='recipientID',
        ),
        migrations.AddField(
            model_name='contract',
            name='dateCreated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='contract',
            name='flagged',
            field=models.BooleanField(default=None, verbose_name=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='issuerID',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=None, verbose_name=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='returned',
            field=models.BooleanField(default=None, verbose_name=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.contract'),
        ),
    ]
