# Generated by Django 4.1.7 on 2023-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contract_items_remove_item_recipientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
