# Generated by Django 4.1.7 on 2023-06-10 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_updated_at_alter_contract_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='sharedContracts',
            field=models.ManyToManyField(to='core.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sharedWith',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
