# Generated by Django 4.1.7 on 2023-07-01 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contract_sharedwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='sharedWith',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
