# Generated by Django 4.1.7 on 2023-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contract_sharedwith'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='issuerID',
            new_name='merchantID',
        ),
        migrations.AddField(
            model_name='contract',
            name='cards_used',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='merchantAddress',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='merchantLocNumber',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='cardInfo',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemCategory',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='itemSku',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='originalVendor',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='paymentMethod',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='returnedBy',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dateCreated',
            field=models.DateTimeField(default=None),
        ),
    ]
