# Generated by Django 4.1.7 on 2023-07-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_issuerid_contract_merchantid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='returnedBy',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
