# Generated by Django 4.1.7 on 2023-07-08 22:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contract_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='sharedContracts',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientID', models.CharField(default=None, max_length=100)),
                ('merchantID', models.CharField(default=None, max_length=100)),
                ('merchantLocNumber', models.CharField(default=None, max_length=100)),
                ('merchantAddress', models.CharField(default=None, max_length=100)),
                ('invoiceID', models.CharField(default=None, max_length=100)),
                ('dateCreated', models.DateTimeField(default=None)),
                ('flagged', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0.0)),
                ('cards_used', models.CharField(max_length=4, null=True)),
                ('transactionHistory', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=100), default=list, size=None)),
                ('sharedWith', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='sharedInvoices',
            field=models.ManyToManyField(to='core.invoice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
