# Generated by Django 4.1.7 on 2023-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_appuser_sharedcontracts_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phoneVerifed',
            field=models.BooleanField(default=False),
        ),
    ]
