# Generated by Django 4.2.4 on 2023-08-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_unverifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='regComplete',
            field=models.BooleanField(default=False),
        ),
    ]
