# Generated by Django 4.2.4 on 2023-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appuser_regcomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='uid',
            new_name='uuid',
        ),
    ]
