# Generated by Django 4.2.7 on 2023-12-27 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('merchantID', models.CharField(default=None, max_length=100)),
                ('merchantMasterPassword', models.CharField(default=None, max_length=100)),
                ('merchantAPIKey', models.CharField(default=None, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnverifiedMerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(default=None, max_length=100)),
                ('businessAddress', models.CharField(default=None, max_length=100)),
                ('businessType', models.CharField(default=None, max_length=100)),
                ('industry', models.CharField(default=None, max_length=100)),
                ('primaryContactName', models.CharField(default=None, max_length=100)),
                ('primaryPhoneNumber', models.CharField(default=None, max_length=100)),
                ('primaryEmailAddress', models.CharField(default=None, max_length=100)),
                ('numRegisters', models.CharField(default=None, max_length=100)),
                ('dateCreated', models.DateTimeField(default=None)),
                ('temporaryUserID', models.CharField(default=None, unique=True)),
                ('temporaryPassword', models.CharField(default=None, unique=True)),
                ('confirmationID', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='merchantName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
