# Generated by Django 4.2.6 on 2024-03-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merchantaccount_unverifiedmerchantaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unverifiedmerchantaccount',
            old_name='confirmationID',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='merchantaccount',
            name='merchantAPIKey',
        ),
        migrations.RemoveField(
            model_name='merchantaccount',
            name='merchantMasterPassword',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='businessAddress',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='businessName',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='businessType',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='numRegisters',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='primaryContactName',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='primaryEmailAddress',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='primaryPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='temporaryPassword',
        ),
        migrations.RemoveField(
            model_name='unverifiedmerchantaccount',
            name='temporaryUserID',
        ),
        migrations.AddField(
            model_name='apikey',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.merchantaccount'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='usageThisMonth',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='businessAddress',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='businessName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='businessType',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='industry',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='masterPassword',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='numRegisters',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='primaryContactName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='primaryEmailAddress',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='primaryPhoneNumber',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='uuid',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='unverifiedmerchantaccount',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='merchantID',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
