# Generated by Django 4.2.6 on 2024-03-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_confirmationid_unverifiedmerchantaccount_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantaccount',
            name='masterPassword',
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
