# Generated by Django 4.2.6 on 2024-03-17 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_merchantaccount_masterpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantaccount',
            name='last_login',
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='usageThisMonth',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
