# Generated by Django 4.2.6 on 2024-03-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_merchantaccount_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantaccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='merchantaccount',
            name='primaryEmailAddress',
        ),
        migrations.RemoveField(
            model_name='merchantaccount',
            name='uuid',
        ),
    ]
